---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install maven installer dependencies
      ansible.builtin.package:
        name:
          - tar
        state: present
      changed_when: false
    - name: Install maven test dependencies
      ansible.builtin.package:
        name:
          - which
        state: present
      when: ansible_os_family == 'RedHat'
      changed_when: false
    # https://github.com/debuerreotype/debuerreotype/issues/10
    - name: Create missing man directory
      ansible.builtin.file:
        path: /usr/share/man/man1
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
      when: ansible_os_family == 'Debian'
      changed_when: false
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  become: true
