---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  roles:
    - role: ecgalaxy.bootstrap
    - role: ecgalaxy.java_openjdk
  tasks:
  - name: Check maven version
    ansible.builtin.command: mvn --version
    register: output
  - name: Assert that maven is installed
    ansible.builtin.assert:
      that:
      - "'Maven {{ maven_version }}' in output.stdout"
